import React from 'react';
import { useEffect, useMemo, useState } from 'react';
import { endpoints } from './api';

const ICONS = { home:'⌂', shops:'⌘', tasks:'✓', team:'♧', insight:'◔', settings:'⚙', plus:'+', search:'⌕', sun:'☼', moon:'☾', pin:'⌖', phone:'◒', arrow:'→', more:'•••', filter:'≡', check:'✓', close:'×', bell:'◌' };
const sampleTasks = [
  { id: 1048, shopId: 1, shopName: 'Downtown Service Hub', customerName: 'Meera Krishnan', customerPhone: '+91 98765 41008', address: '18, Cathedral Road, Gopalapuram', issueType: 'COMPLAINT', description: 'Air conditioner is leaking water from the indoor unit.', priority: 'HIGH', status: 'IN_PROGRESS', assignedTechnician: { id: 3, name: 'Arun Kumar' }, createdAt: '2026-08-08T08:30:00Z' },
  { id: 1047, shopId: 1, shopName: 'Downtown Service Hub', customerName: 'Rajesh Iyer', customerPhone: '+91 98400 12791', address: '45, Lake View Road, Nungambakkam', issueType: 'SALES', description: 'New washing machine installation and demo.', priority: 'NORMAL', status: 'ASSIGNED', assignedTechnician: { id: 4, name: 'Priya S' }, createdAt: '2026-08-08T07:10:00Z' },
  { id: 1046, shopId: 2, shopName: 'Velachery Care Centre', customerName: 'Anitha Suresh', customerPhone: '+91 97891 63524', address: '12, Taramani Main Road, Velachery', issueType: 'SERVICE', description: 'Annual maintenance service is due.', priority: 'LOW', status: 'CREATED', createdAt: '2026-08-07T14:00:00Z' },
  { id: 1045, shopId: 1, shopName: 'Downtown Service Hub', customerName: 'S. Prakash', customerPhone: '+91 99403 98703', address: '8, Harrington Road, Chetpet', issueType: 'COMPLAINT', description: 'Refrigerator not cooling consistently.', priority: 'URGENT', status: 'COMPLETED', assignedTechnician: { id: 3, name: 'Arun Kumar' }, createdAt: '2026-08-07T11:00:00Z' }
];
const sampleShops = [{ id: 1, name: 'Downtown Service Hub', address: 'Chennai Central', users: 9, active: 14 }, { id: 2, name: 'Velachery Care Centre', address: 'Velachery, Chennai', users: 6, active: 7 }, { id: 3, name: 'Anna Nagar Workshop', address: 'Anna Nagar, Chennai', users: 5, active: 4 }];
const technicians = [{ id: 3, name: 'Arun Kumar', specialty: 'Appliances', open: 3, initials: 'AK' }, { id: 4, name: 'Priya S', specialty: 'Installation', open: 2, initials: 'PS' }, { id: 5, name: 'Vikram R', specialty: 'HVAC', open: 4, initials: 'VR' }];
const navFor = role => role === 'COMMANDER' ? [['home','Overview'],['shops','Shops'],['tasks','All tasks'],['team','People'],['insight','Insights']] : role === 'ADMIN' ? [['home','Overview'],['tasks','Tasks'],['team','Technicians'],['insight','Insights']] : [['home','My work'],['tasks','Requests'],['insight','Activity']];
const statusLabel = value => ({ CREATED:'Created', ASSIGNED:'Assigned', IN_PROGRESS:'In progress', COMPLETED:'Completed', CANCELLED:'Cancelled' }[value] || value?.replaceAll('_',' '));
const dateText = value => new Intl.DateTimeFormat('en-IN', { day:'numeric', month:'short', hour:'numeric', minute:'2-digit' }).format(new Date(value));

function Icon({ name }) { return <span className={`icon i-${name}`} aria-hidden>{ICONS[name]}</span>; }
function Chip({ value, kind = 'status' }) { return <span className={`chip ${kind}-${value?.toLowerCase()}`}>{kind === 'priority' && <span className="priority-dot" />}{statusLabel(value)}</span>; }

export default function App() {
  const [role, setRole] = useState(localStorage.getItem('slms-role') || 'COMMANDER');
  const [theme, setTheme] = useState(localStorage.getItem('slms-theme') || 'light');
  const [page, setPage] = useState('Overview'); const [tasks, setTasks] = useState(sampleTasks); const [shops, setShops] = useState(sampleShops);
  const [activeShop, setActiveShop] = useState(1); const [search, setSearch] = useState(''); const [modal, setModal] = useState(null); const [toast, setToast] = useState(''); const [loading, setLoading] = useState(false);
  const demo = import.meta.env.VITE_DEMO_MODE !== 'false';
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('slms-theme', theme); }, [theme]);
  useEffect(() => { localStorage.setItem('slms-role', role); setPage(role === 'TECHNICIAN' ? 'My work' : 'Overview'); }, [role]);
  useEffect(() => { if (!demo) loadData(); }, [role, activeShop]);
  const loadData = async () => { setLoading(true); try { const data = await endpoints.tasks(role === 'ADMIN' ? activeShop : undefined); setTasks(data); if (role === 'COMMANDER') setShops(await endpoints.shops()); } catch (e) { tell(`Could not reach API: ${e.message}`); } finally { setLoading(false); } };
  const tell = message => { setToast(message); setTimeout(() => setToast(''), 3200); };
  const filteredTasks = useMemo(() => tasks.filter(t => role !== 'TECHNICIAN' || t.assignedTechnician?.id === 3).filter(t => `${t.customerName} ${t.address} ${t.id}`.toLowerCase().includes(search.toLowerCase())), [tasks, search, role]);
  const activeTasks = filteredTasks.filter(t => !['COMPLETED','CANCELLED'].includes(t.status));
  const done = filteredTasks.filter(t => t.status === 'COMPLETED').length;
  const changeStatus = async (task, status) => { try { if (!demo) await endpoints.updateTaskStatus(task.id, { status, notes: '' }); setTasks(current => current.map(item => item.id === task.id ? { ...item, status } : item)); setModal(null); tell(`Request #${task.id} marked ${statusLabel(status).toLowerCase()}.`); } catch(e) { tell(e.message); } };
  const createShop = async form => { const payload = { id: Date.now(), ...form, users: 0, active: 0 }; try { const created = demo ? payload : await endpoints.createShop(form); setShops(current => [created, ...current]); setModal(null); tell(`${form.name} is ready to use.`); } catch(e) { tell(e.message); } };
  const createTask = async form => { const payload = { id: Date.now(), shopId: role === 'ADMIN' ? activeShop : Number(form.shopId), shopName: shops.find(s => s.id === Number(form.shopId))?.name || 'Downtown Service Hub', status:'CREATED', priority:'NORMAL', issueType:'SERVICE', createdAt:new Date().toISOString(), ...form }; try { const created = demo ? payload : await endpoints.createTask(payload); setTasks(current => [created, ...current]); setModal(null); tell(`Request #${created.id} created.`); } catch(e) { tell(e.message); } };
  const assign = (task, technician) => { setTasks(current => current.map(item => item.id === task.id ? { ...item, assignedTechnician: technician, status: item.status === 'CREATED' ? 'ASSIGNED' : item.status } : item)); setModal(null); tell(`${technician.name} has been assigned.`); };
  const title = page === 'My work' ? 'Good morning, Arun' : page;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="logo">U</div><span>loopwork</span></div><nav>{navFor(role).map(([icon, label]) => <button key={label} onClick={() => setPage(label)} className={page === label ? 'nav-active' : ''}><Icon name={icon}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button onClick={() => setPage('Settings')} className={page === 'Settings' ? 'nav-active' : ''}><Icon name="settings"/><span>Settings</span></button><div className="profile"><div className="avatar">AK</div><div><strong>Arun Kumar</strong><small>{role === 'COMMANDER' ? 'Commander' : role === 'ADMIN' ? 'Shop admin' : 'Technician'}</small></div><Icon name="more"/></div></div></aside>
    <main><header><div className="mobile-brand"><div className="logo">U</div>loopwork</div><div><p className="eyebrow">{role === 'TECHNICIAN' ? 'Downtown Service Hub' : role === 'ADMIN' ? 'Service operations' : 'Multi-shop operations'}</p><h1>{title}</h1></div><div className="header-actions"><button className="icon-button" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')} aria-label="Toggle colour theme"><Icon name={theme === 'light' ? 'moon' : 'sun'}/></button><button className="icon-button notification"><Icon name="bell"/><i/></button><div className="role-select"><span>Viewing as</span><select value={role} onChange={e => setRole(e.target.value)}><option>COMMANDER</option><option>ADMIN</option><option>TECHNICIAN</option></select></div></div></header>
    <div className="content">{loading && <div className="loading">Refreshing workspace…</div>}{page === 'Overview' || page === 'My work' ? <Overview role={role} tasks={filteredTasks} shops={shops} activeTasks={activeTasks} done={done} onPage={setPage} onTask={setModal} onCreate={() => setModal('task')} /> : page === 'Shops' ? <Shops shops={shops} onCreate={() => setModal('shop')} /> : page === 'Tasks' || page === 'All tasks' || page === 'Requests' ? <Tasks tasks={filteredTasks} search={search} setSearch={setSearch} onTask={setModal} onCreate={() => setModal('task')} role={role} /> : page === 'Technicians' || page === 'People' ? <People role={role} technicians={technicians} /> : page === 'Insights' || page === 'Activity' ? <Insights tasks={tasks} /> : <Settings theme={theme} setTheme={setTheme} />}</div>
    </main>
    <nav className="bottom-nav">{navFor(role).slice(0,4).map(([icon,label]) => <button key={label} onClick={() => setPage(label)} className={page === label ? 'nav-active' : ''}><Icon name={icon}/><span>{label}</span></button>)}</nav>
    {modal === 'task' && <TaskForm shops={shops} role={role} activeShop={activeShop} onClose={() => setModal(null)} onSave={createTask}/>} {modal === 'shop' && <ShopForm onClose={() => setModal(null)} onSave={createShop}/>} {modal?.id && <TaskDetail task={modal} role={role} technicians={technicians} onClose={() => setModal(null)} onStatus={changeStatus} onAssign={assign}/>} {toast && <div className="toast"><Icon name="check"/>{toast}</div>}
  </div>;
}

function Overview({ role, tasks, shops, activeTasks, done, onPage, onTask, onCreate }) { const isTech = role === 'TECHNICIAN'; return <>
  <section className="hero"><div><span className="pulse"><i/>Live operations</span><h2>{isTech ? `${activeTasks.length} jobs need your attention` : `${activeTasks.length} service requests in motion`}</h2><p>{isTech ? 'Keep customers informed by updating every job as you go.' : 'Everything across your service network, in one calm place.'}</p></div><button className="primary" onClick={onCreate}><Icon name="plus"/>{isTech ? 'Log a request' : 'Create request'}</button></section>
  <section className="stat-grid"><Stat icon="tasks" label={isTech ? 'Assigned to you' : 'Open requests'} value={activeTasks.length} change="8% from last week" tone="violet"/><Stat icon="check" label="Completed today" value={done || 12} change="3 more than yesterday" tone="green"/><Stat icon="team" label={isTech ? 'Customer visits' : 'Active technicians'} value={isTech ? '04' : '18'} change={isTech ? '2 scheduled today' : '2 currently available'} tone="orange"/><Stat icon="insight" label="Completion rate" value="92%" change="On track this month" tone="blue"/></section>
  <section className="section-heading"><div><h2>{isTech ? 'Your next jobs' : 'Priority requests'}</h2><p>Keep the day moving without losing context.</p></div><button className="text-button" onClick={() => onPage(isTech ? 'Requests' : 'Tasks')}>View all <Icon name="arrow"/></button></section>
  <div className="dashboard-grid"><div className="card request-list">{activeTasks.slice(0,3).map(task => <TaskRow key={task.id} task={task} onClick={() => onTask(task)}/>)}</div><div className="card progress-card"><div><span className="eyebrow">TODAY'S PULSE</span><h3>{done || 12} requests resolved</h3><p>Your team is pacing ahead of its daily average.</p></div><div className="donut"><b>92<small>%</small></b></div><div className="progress-legend"><span><i className="violet"/>Completed</span><strong>92%</strong><span><i className="muted"/>In progress</span><strong>8%</strong></div></div></div>
  {!isTech && <><section className="section-heading shop-heading"><div><h2>Shop health</h2><p>A quick look at your service locations.</p></div>{role === 'COMMANDER' && <button className="text-button" onClick={() => onPage('Shops')}>Manage shops <Icon name="arrow"/></button>}</section><div className="shop-grid">{shops.slice(0,3).map(shop => <div className="card shop-card" key={shop.id}><div className="shop-mark">{shop.name[0]}</div><div><h3>{shop.name}</h3><p><Icon name="pin"/>{shop.address}</p></div><button className="round-more"><Icon name="more"/></button><div className="shop-metrics"><span><b>{shop.active}</b> active jobs</span><span><b>{shop.users}</b> team members</span></div></div>)}</div></>}
</>; }
function Stat({ icon, label, value, change, tone }) { return <div className="card stat"><div className={`stat-icon ${tone}`}><Icon name={icon}/></div><div><p>{label}</p><h2>{value}</h2><small>{change}</small></div></div>; }
function TaskRow({ task, onClick }) { return <button className="task-row" onClick={onClick}><div className="task-icon"><Icon name={task.issueType === 'INSTALLATION' ? 'plus' : 'tasks'}/></div><div className="task-main"><div><h3>{task.customerName}</h3><span>#{task.id} · {task.issueType?.toLowerCase()}</span></div><p><Icon name="pin"/>{task.address}</p></div><Chip value={task.status}/><Icon name="arrow"/></button>; }
function Tasks({ tasks, search, setSearch, onTask, onCreate, role }) { return <><section className="toolbar"><div className="search"><Icon name="search"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search customer, request or address" /></div><button className="secondary"><Icon name="filter"/>Filter</button><button className="primary" onClick={onCreate}><Icon name="plus"/>New request</button></section><div className="task-board">{['CREATED','ASSIGNED','IN_PROGRESS','COMPLETED'].map(status => <div className="board-column" key={status}><div className="column-title"><span>{statusLabel(status)}</span><b>{tasks.filter(t => t.status === status).length}</b></div>{tasks.filter(t => t.status === status).map(task => <button className="task-tile" onClick={() => onTask(task)} key={task.id}><div><Chip value={task.priority} kind="priority"/><span className="task-id">#{task.id}</span></div><h3>{task.customerName}</h3><p><Icon name="pin"/>{task.address}</p><footer><span>{task.assignedTechnician?.name || 'Unassigned'}</span><Chip value={task.status}/></footer></button>)}</div>)}</div></>; }
function Shops({ shops, onCreate }) { return <><section className="page-actions"><div><h2>Your locations</h2><p>Create and oversee service locations from one workspace.</p></div><button className="primary" onClick={onCreate}><Icon name="plus"/>Add shop</button></section><div className="shops-page">{shops.map(shop => <div className="card shop-large" key={shop.id}><div className="shop-mark">{shop.name[0]}</div><div><h2>{shop.name}</h2><p><Icon name="pin"/>{shop.address}</p></div><div className="shop-large-stats"><span><b>{shop.active}</b><small>active jobs</small></span><span><b>{shop.users}</b><small>people</small></span></div><button className="secondary">Open <Icon name="arrow"/></button></div>)}</div></>; }
function People({ technicians }) { return <><section className="page-actions"><div><h2>Field team</h2><p>Availability and workload for your technicians.</p></div><button className="primary"><Icon name="plus"/>Invite technician</button></section><div className="people-grid">{technicians.map(person => <div className="card person" key={person.id}><div className="avatar large">{person.initials}</div><h2>{person.name}</h2><p>{person.specialty}</p><span className="available"><i/>Available now</span><div><b>{person.open}</b><small>open jobs</small></div><button className="secondary">View workload</button></div>)}</div></>; }
function Insights({ tasks }) { const total = tasks.length || 1; return <><section className="page-actions"><div><h2>Operational insights</h2><p>A clear picture of work across the last 30 days.</p></div><button className="secondary">Last 30 days ▾</button></section><div className="insight-grid"><div className="card chart"><h3>Request volume</h3><div className="bars">{[43,62,50,78,65,90,72,84,58,96,82,70].map((height,i) => <i key={i} style={{height:`${height}%`}} />)}</div><div className="chart-axis"><span>Week 1</span><span>Week 2</span><span>Week 3</span><span>This week</span></div></div><div className="card breakdown"><h3>Resolution mix</h3><div className="ring"><b>{Math.round(tasks.filter(t => t.status === 'COMPLETED').length / total * 100) || 92}%</b></div><p>resolved within the service target</p><span><i className="violet"/>On time <b>92%</b></span><span><i className="orange"/>At risk <b>8%</b></span></div></div></>; }
function Settings({ theme, setTheme }) { return <div className="card settings"><h2>Preferences</h2><p>Choose the workspace appearance that feels right for you.</p><div className="setting-row"><div><h3>Colour theme</h3><span>Use light or dark appearance.</span></div><div className="theme-toggle"><button className={theme === 'light' ? 'selected' : ''} onClick={() => setTheme('light')}><Icon name="sun"/>Light</button><button className={theme === 'dark' ? 'selected' : ''} onClick={() => setTheme('dark')}><Icon name="moon"/>Dark</button></div></div><div className="setting-row"><div><h3>Mobile installation</h3><span>Install Loopwork from your browser’s “Add to Home Screen” menu.</span></div><span className="pwa-badge">PWA ready</span></div></div>; }
function Modal({ title, children, onClose }) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e => e.stopPropagation()}><div className="modal-title"><h2>{title}</h2><button className="icon-button" onClick={onClose}><Icon name="close"/></button></div>{children}</div></div>; }
function TaskForm({ shops, role, activeShop, onClose, onSave }) { const [form,setForm] = useState({ shopId:String(activeShop), customerName:'',customerPhone:'',address:'',description:'',priority:'NORMAL',issueType:'SERVICE' }); const change = e => setForm({...form,[e.target.name]:e.target.value}); return <Modal title="Create service request" onClose={onClose}><form onSubmit={e => {e.preventDefault();onSave(form)}}><div className="form-grid">{role === 'COMMANDER' && <label>Shop<select name="shopId" value={form.shopId} onChange={change}>{shops.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label>}<label>Customer name<input required name="customerName" value={form.customerName} onChange={change} placeholder="Customer's full name"/></label><label>Phone number<input required name="customerPhone" value={form.customerPhone} onChange={change} placeholder="+91 98765 43210"/></label><label className="full">Service address<input name="address" value={form.address} onChange={change} placeholder="House, street, neighbourhood"/></label><label>Request type<select name="issueType" value={form.issueType} onChange={change}><option>SALES</option><option>SERVICE</option><option>COMPLAINT</option></select></label><label>Priority<select name="priority" value={form.priority} onChange={change}><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><label className="full">Service notes<textarea name="description" value={form.description} onChange={change} placeholder="What needs attention?"/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Create request</button></div></form></Modal>; }
function ShopForm({ onClose, onSave }) { const [form,setForm] = useState({name:'',address:''}); return <Modal title="Add a new shop" onClose={onClose}><form onSubmit={e => { e.preventDefault(); onSave(form); }}><div className="form-grid"><label className="full">Shop name<input required value={form.name} onChange={e => setForm({...form,name:e.target.value})} placeholder="e.g. Adyar Service Centre"/></label><label className="full">Address<input value={form.address} onChange={e => setForm({...form,address:e.target.value})} placeholder="Neighbourhood, city"/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Create shop</button></div></form></Modal>; }
function TaskDetail({ task, role, technicians, onClose, onStatus, onAssign }) { const next = task.status === 'CREATED' ? 'ASSIGNED' : task.status === 'ASSIGNED' ? 'IN_PROGRESS' : task.status === 'IN_PROGRESS' ? 'COMPLETED' : null; return <Modal title={`Request #${task.id}`} onClose={onClose}><div className="detail"><div className="detail-top"><div><Chip value={task.priority} kind="priority"/><h2>{task.customerName}</h2><p><Icon name="pin"/>{task.address}</p><p><Icon name="phone"/>{task.customerPhone}</p></div><Chip value={task.status}/></div><div className="detail-block"><span>Service request</span><h3>{task.issueType}</h3><p>{task.description || 'No additional service notes were added.'}</p></div><div className="detail-block"><span>Assigned technician</span><h3>{task.assignedTechnician?.name || 'Not assigned yet'}</h3></div>{role !== 'TECHNICIAN' && <div className="assign-list"><span>Assign technician</span>{technicians.map(person => <button key={person.id} onClick={() => onAssign(task, person)}><div className="avatar">{person.initials}</div><div><b>{person.name}</b><small>{person.open} open jobs</small></div>{task.assignedTechnician?.id === person.id && <Icon name="check"/>}</button>)}</div>}{next && <button className="primary full-button" onClick={() => onStatus(task, next)}>{next === 'IN_PROGRESS' ? 'Start service' : next === 'COMPLETED' ? 'Mark completed' : 'Mark assigned'} <Icon name="arrow"/></button>}</div></Modal>; }
